version: '3.8'
services:
  smtp:
    image: marcopas/docker-mailslurper
    restart: always
    ports:
      - '2500:2500'
      - '8085:8085'
      - '8086:8080'
  account-db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth-service
    ports:
      - '5432:5432'
  storage-db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: storage-service
    ports:
      - '5433:5432'
  mail-db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mail-service
    ports:
      - '5434:5432'