spring:
  autoconfigure:
    exclude[0]: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
    exclude[1]: org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
  application:
    name: auth-service
  liquibase:
    enabled: true
    contexts: ${LIQUIBASE_CONTEXTS:}
    change-log: classpath:/changelog/db.changelog-master.yaml
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/auth-service
    username: postgres
    password: postgres
    hikari:
      connection-timeout: 80000
      maximum-pool-size: ${DATASOURCE_CONNECTIONS:5}
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: validate