spring:
  application:
    name: auth-service
  liquibase:
    enabled: true
    contexts: ${LIQUIBASE_CONTEXTS:}
    change-log: classpath:/changelog/db.changelog-master.yaml
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/auth-service
    username: postgres
    password: postgres
    hikari:
      connection-timeout: 80000
      maximum-pool-size: ${DATASOURCE_CONNECTIONS:5}
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: validate

# TODO: implement rsa key pair encoding algorithm
jwt:
  secret: secretKey124214
  accessTokenExpiry: 600000
  refreshTokenExpiry: 320000

# TODO: disable swagger-ui, api-docs in production profiles
springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true